- name: ensure the user exists
  user:
    name: "{{ shell_user }}"

- name: set default user home directory
  set_fact:
    shell_user_home: /home/{{ shell_user }}

- name: set root user home directory
  set_fact:
    shell_user_home: /{{ shell_user }}
  when: shell_user == 'root'

# ======================================================================
# Required software packages
# ======================================================================
- name: install required apt packages
  yum:
    name: "{{ item }}"
  with_items:
  - vim
  - zsh
  - git
  - ctags
  - unzip
  - tar
  - wget

# ======================================================================
# Oh my ZSH
# ======================================================================

- name: clone oh-my-zsh repository
  git:
    accept_hostkey: yes
    dest: /opt/oh-my-zsh
    repo: git://github.com/robbyrussell/oh-my-zsh.git

- name: change oh-my-zsh permissions
  shell: chmod -R 755 /opt/oh-my-zsh

- name: ignore filemode in oh-my-zsh
  shell: git config core.filemode false
  args:
    chdir: /opt/oh-my-zsh

- name: copy .zshrc
  template:
    src: dot_zshrc.j2
    dest: "{{ shell_user_home }}/.zshrc"
    owner: "{{ shell_user }}"
    group: "{{ shell_user }}"
  when: shell_zsh_enabled

- file:
    dest: "{{ shell_user_home }}/.zshrc"
    state: absent
  when: not shell_zsh_enabled

- name: change users shell
  shell: chsh -s /bin/zsh {{ shell_user }}
  when: shell_zsh_enabled

# ======================================================================
# VIM package
# ======================================================================
- name: Download the ultimate vim configuration.
  git:
    accept_hostkey: yes
    dest: /opt/vim_runtime
    repo: git://github.com/amix/vimrc.git

- name: change vim_runtime permissions
  shell: chmod 755 /opt/vim_runtime

- name: ignore filemode in amix/vimrc
  shell: git config core.filemode false
  args:
    chdir: /opt/vim_runtime

- name: copy .vimrc for dork user
  template:
    src: dot_vimrc.j2
    dest: "{{ shell_user_home }}/.vimrc"
    owner: "{{ shell_user }}"
    group: "{{ shell_user }}"
  when: shell_vim_enabled

- file:
    dest: "{{ shell_user_home }}/.vimrc"
    state: absent
  when: not shell_vim_enabled
